In [11]:
class Pokemon:
    def __init__(self, id, name, type1, type2, total, hp, attack, defense, sp_atk, sp_def, speed, generation, legendary):
        self.id = id
        self.name = name
        self.type1 = type1
        self.type2 = type2
        self.total = total
        self.hp = hp
        self.attack = attack
        self.defense = defense
        self.sp_atk = sp_atk
        self.sp_def = sp_def
        self.speed = speed
        self.generation = generation
        self.legendary = legendary
    
    def __repr__(self):
        return f"Pokemon({self.name}, Type: {self.type1}/{self.type2})"

In [12]:
import pandas as pd
import csv

path = r'C:\Users\USER\PycharmProjects\Mid_Project\Mid_Project\Mid_Project\Docs\Pokemon.csv'

# Load the dataset into a pandas DataFrame
pokemon_df = pd.read_csv(path)

pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099,1021,Raging Bolt,Electric,Dragon,590,125,73,91,137,89,75,9,True
1100,1022,Iron Boulder,Rock,Dragon,590,90,120,80,68,108,124,9,True
1101,1023,Iron Crown,Steel,Psychic,590,90,72,100,122,108,98,9,True
1102,1024,Terapagos,Normal,NaN,700,160,105,110,130,110,85,9,True
1103,1025,Pecharunt,Poison,Ghost,600,88,88,160,88,88,88,9,True

In [13]:

# List to hold all the Pokemon objects
pokemon_objects = []

# Iterate over each row in the DataFrame and create a Pokemon object
for index, row in pokemon_df.iterrows():
    pokemon = Pokemon(
        id=row['#'],
        name=row['Name'],
        type1=row['Type 1'],
        type2=row['Type 2'] if pd.notnull(row['Type 2']) else 'None',  # Handling potential NaN values
        total=row['Total'],
        hp=row['HP'],
        attack=row['Attack'],
        defense=row['Defense'],
        sp_atk=row['Sp. Atk'],
        sp_def=row['Sp. Def'],
        speed=row['Speed'],
        generation=row['Generation'],
        legendary=row['Legendary']
    )
    pokemon_objects.append(pokemon)

# Example: Print the first 5 Pokemon objects to verify
for pokemon in pokemon_objects[:5]:
    print(pokemon)

Pokemon(Bulbasaur, Type: Grass/Poison)
Pokemon(Ivysaur, Type: Grass/Poison)
Pokemon(Venusaur, Type: Grass/Poison)
Pokemon(VenusaurMega Venusaur, Type: Grass/Poison)
Pokemon(Charmander, Type: Fire/None)

In [15]:
## Cleaning and sorting

pokemon_df = pokemon_df.drop_duplicates()

pokemon_df = pokemon_df.sort_values(by='Name', ascending=True)

pokemon_df = pokemon_df.reset_index(drop=True)

In [17]:
print (pokemon_df)

        #                     Name   Type 1  Type 2  Total   HP  Attack  \
0     460                Abomasnow    Grass     Ice    494   90      92
1     460  AbomasnowMega Abomasnow    Grass     Ice    594   90     132
2      63                     Abra  Psychic     NaN    310   25      20
3     359                    Absol     Dark     NaN    465   65     130
4     359          AbsolMega Absol     Dark     NaN    565   65     150
...   ...                      ...      ...     ...    ...  ...     ...
1099  571                  Zoroark     Dark     NaN    510   60     105
1100  570                    Zorua     Dark     NaN    330   40      65
1101   41                    Zubat   Poison  Flying    245   40      45
1102  634                 Zweilous     Dark  Dragon    420   72      85
1103  718         Zygarde50% Forme   Dragon  Ground    600  108     100

      Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0          75       92       85     60           4      False
1         105      132      105     30           4      False
2          15      105       55     90           1      False
3          60       75       60     75           3      False
4          60      115       60    115           3      False
...       ...      ...      ...    ...         ...        ...
1099       60      120       60    105           5      False
1100       40       80       40     65           5      False
1101       35       30       40     55           1      False
1102       70       65       70     58           5      False
1103      121       81       95     95           6       True

[1104 rows x 13 columns]